export const HANDLES_PRODUCT_KIT = [
  'productkit',
  'productkit__item',
  'productkit__image',
  'productkit__info',
  'productkit__info--name',
  'productkit__info--priceWrapper',
  'productkit__info--listPrice',
  'productkit__info--bestPrice',
  'productkit__info--skuWrapper',
  'productkit__info--skuWrapper__title',
  'productkit__info--skuWrapper__item',
  'productkit__info--skuWrapper__item--unavailable',
  'productkit__info--skuWrapper__skuList',
  'productkit__info--skuWrapper__remove',
  'productkit__sizeguidebutton',
  'productkit__resume',
  'productkit__resume--selected',
  'productkit__resume--strong',
  'productkit__resume--price',
  'productkit__resume--installments',
  'productkit__buybutton',
] as const
